inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'config/*'
    - 'config/initializers/*'
    - 'config/environments/*'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/ClassLength:
  Max: 200
